# Generated by Django 3.0.5 on 2020-04-20 07:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200420_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
