from django.contrib import admin

from .models import *

admin.site.register(Industry)
admin.site.register(Keyword)
admin.site.register(Qualification)
admin.site.register(Country)
admin.site.register(State)
admin.site.register(Skill)
admin.site.register(FunctionalArea)
admin.site.register(Language)
admin.site.register(UserLanguage)
admin.site.register(City)
admin.site.register(Company)
admin.site.register(EducationInstitue)
admin.site.register(EmploymentHistory)
admin.site.register(Degree)
admin.site.register(EducationDetails)
admin.site.register(Project)
admin.site.register(TechnicalSkill)
admin.site.register(User)
admin.site.register(Attachment)
admin.site.register(Ticket)
admin.site.register(Comment)
admin.site.register(UserEmail)

admin.site.register(Linkedin)
admin.site.register(Google)
admin.site.register(GitHub)
admin.site.register(LinkedinGroup)
admin.site.register(LinkedinFriend)
admin.site.register(InterviewLocation)
admin.site.register(AgencyCompanyBranch)
admin.site.register(AgencyCompanyCatogery)
admin.site.register(AgencyContractDetails)
admin.site.register(AgencyCompany)
# admin.site.register(JobPostManager)
admin.site.register(JobPost)
admin.site.register(LinkedinPost)
admin.site.register(AgencyResume)
admin.site.register(AppliedJobs)

admin.site.register(simplecontact)
admin.site.register(MailTemplate)
admin.site.register(SentMail)
admin.site.register(JobAlert)
admin.site.register(SearchResult)
admin.site.register(Subscriber)
admin.site.register(VisitedJobs)
admin.site.register(Menu)
admin.site.register(DailySearchLog)
admin.site.register(AgencyApplicants)
admin.site.register(AgencyRecruiterJobposts)
# admin.site.register(skills_update)
admin.site.register(AgencyWorkLog)
admin.site.register(BlogAttachment)
admin.site.register(Solution)

admin.site.register(Question)
admin.site.register(AssessmentData)
admin.site.register(CredentialsModel)

